# Generated by Django 2.2.7 on 2019-11-26 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='states',
            options={'verbose_name_plural': 'states'},
        ),
    ]
