# Generated by Django 2.2.7 on 2019-11-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20191126_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='state_capital',
            field=models.CharField(max_length=250, verbose_name='Capital'),
        ),
        migrations.AlterField(
            model_name='states',
            name='state_name',
            field=models.CharField(max_length=250, verbose_name='State Name'),
        ),
    ]
