# Generated by Django 2.2.7 on 2019-11-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_auto_20191126_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='total_districts',
            field=models.IntegerField(blank=True),
        ),
    ]
