# Generated by Django 2.2.7 on 2019-11-26 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_auto_20191126_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
